"""AUTO-GENERATED by scripts/gen_shared.py — do not edit by hand.

Source of truth: agentix/contracts/*.schema.json + constants/cluster.yaml.
Regenerate with `python scripts/gen_shared.py` after any contract/cluster change.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

# ── Broker (NATS JetStream) — from constants/cluster.yaml :: broker ───────────
NATS_URL = "nats://10.0.99.1:4222"
JOBS_SUBJECT = "ludo.jobs"
JOBS_CANCEL_SUBJECT = "ludo.jobs.cancel"
EVENTS_SUBJECT_PREFIX = "ludo.events"  # ludo.events.<session_id>
CHECKPOINTS_SUBJECT_PREFIX = "ludo.checkpoints"  # ludo.checkpoints.<session_id>
JOBS_STREAM = "LUDO_JOBS"
EVENTS_STREAM = "LUDO_EVENTS"


def event_subject(session_id: str) -> str:
    """Per-session egress subject for Contract B events."""
    return f"{EVENTS_SUBJECT_PREFIX}.{session_id or 'unknown'}"


def checkpoint_decision_subject(session_id: str) -> str:
    """Per-session operator-decision subject (checkpoint_requested reply channel)."""
    return f"{CHECKPOINTS_SUBJECT_PREFIX}.{session_id or 'unknown'}"


# ── Contract B enums — from contracts/*.schema.json ──────────────────────────
class JobType(StrEnum):
    """Dispatch key (gateway -> agent). Mirror of the job-message schema."""

    EXTRACT = "extract"
    TRANSFORM = "transform"
    LOAD = "load"
    VERIFY = "verify"
    ESTIMATE = "estimate"
    BULK_LOAD = "bulk_load"
    ROLLBACK = "rollback"
    PORT_MODULE = "port_module"
    TRAJECTORIES_REBUILD = "trajectories_rebuild"
    DISCOVER_ORDER = "discover_order"
    BACKFILL_TYPES = "backfill_types"


class EventType(StrEnum):
    """Session-event type (agent -> gateway). Mirror of the session-event schema."""

    SESSION_STARTED = "session_started"
    SESSION_END = "session_end"
    MODEL_STARTED = "model_started"
    MODEL_COMPLETED = "model_completed"
    JOB_STARTED = "job_started"
    JOB_COMPLETED = "job_completed"
    JOB_FAILED = "job_failed"
    TURN_STARTED = "turn_started"
    TURN_COMPLETED = "turn_completed"
    SAFETY_EVENT = "safety_event"
    CHECKPOINT_REQUESTED = "checkpoint_requested"
    VERIFY_STAGE = "verify_stage"


EVENT_TYPES = frozenset(EventType)


# ── Migration lifecycle — from constants/cluster.yaml :: migration.states ─────
# Control-plane Migration.state_index labels (0-indexed). Canonical for every surface.
MIGRATION_STATES: tuple[str, ...] = ('Approved', 'Queued', 'Migrating', 'Test', 'Gap-fix', 'Delivered', 'Deployed')


def migration_state_label(index: int) -> str:
    """Human label for a state_index; falls back to "State N" out of range."""
    return MIGRATION_STATES[index] if 0 <= index < len(MIGRATION_STATES) else f"State {index}"


# ── Contract B models ────────────────────────────────────────────────────────
class JobMessage(BaseModel):
    """gateway -> agent broker payload (ludo.jobs). additionalProperties: false."""

    model_config = ConfigDict(extra="forbid")

    job_id: str
    type: JobType
    account_id: str
    idempotency_key: str | None = None
    session_id: str | None = None
    source: dict[str, Any] | None = None
    target: dict[str, Any] | None = None
    source_version: str | None = None
    target_version: str | None = None
    params: dict[str, Any] = Field(default_factory=dict)
    budget_usd: float | None = None


class SessionEvent(BaseModel):
    """agent -> gateway event envelope (ludo.events.<session_id>). extra allowed."""

    model_config = ConfigDict(extra="allow")

    session_id: str
    type: EventType
    payload: dict[str, Any] = Field(default_factory=dict)
    at: str
    schema_version: str
    checkpoint_required: bool = False
