"""Driver stub code generator.

The stubs are written **structurally** — plain classes, not ``Protocol``
subclasses — matching how the kernel's own adapters are written
(``OpenAIChatDriver``, ``HubleChatDriver``, ``HfSttDriver``). The driver
protocols are ``@runtime_checkable``, so conformance is asserted with
``isinstance``; subclassing them additionally trips mypy on the
``descriptor`` property.

Every template here must stay in step with the real protocols in
``agentix/drivers/{base,chat,embedding,speech}.py``. Drift is caught by
``tests/unit/agentixd/test_scaffold_driver.py``, which execs each rendered
stub and isinstance-checks the result.
"""

from __future__ import annotations

_CHAT_STUB = '''\
"""
{name} — chat driver stub generated by `agentix scaffold driver {name}`.

Implement `complete()`, then register (seam #13):

    # in your app's startup
    from agentix.drivers.factory import register_driver_factory
    from {module_name} import {class_name}

    register_driver_factory("{key}", lambda spec, cfg: {class_name}(spec=spec))

Or skip the factory entirely and point a DriverSpec at this class directly:

    DriverSpec(name="{key}", driver="{module_name}:{class_name}", modality="chat")

See docs/drivers.md for the full driver contract.
"""

from __future__ import annotations

from typing import Any

from agentix.drivers.base import DriverDescriptor
from agentix.drivers.chat import ChatRequest, ChatResponse


class {class_name}:
    """Chat driver for {name} — satisfies `agentix.drivers.chat.ChatDriver`."""

    name = "{key}"
    default_model = "CHANGEME"

    def __init__(self, *, spec: Any = None, api_key: str | None = None) -> None:
        self._spec = spec
        self._api_key = api_key
        if spec is not None and getattr(spec, "model", None):
            self.default_model = spec.model

    @property
    def descriptor(self) -> DriverDescriptor:
        return DriverDescriptor(
            name=self.name,
            type="model",
            modality="chat",
            source="api",
            # Declare "tools" once complete() translates request.tools.
            capabilities=frozenset(),
            default_model=self.default_model,
            pricing_ref=self.default_model,
        )

    async def complete(self, request: ChatRequest) -> ChatResponse:
        """Issue one non-streaming completion.

        Translate `request` into your backend's wire shape, then map the reply
        back onto ChatResponse (`content`, `usage`, `model`, `finish_reason`,
        `tool_calls`). Classify failures as DriverRateLimited /
        DriverUnavailable / DriverInvalidRequest from `agentix.drivers.base` —
        the failover chain branches on their `retryable` flag.
        """
        raise NotImplementedError("{class_name}.complete() not implemented")

    async def aclose(self) -> None:
        """Release underlying resources (HTTP clients, connections)."""
        return None


__all__ = ["{class_name}"]
'''

_EMBEDDING_STUB = '''\
"""
{name} — embedding driver stub generated by `agentix scaffold driver {name}`.

Implement `embed()`, then register (seam #13):

    from agentix.drivers.factory import register_driver_factory
    from {module_name} import {class_name}

    register_driver_factory("{key}", lambda spec, cfg: {class_name}(spec=spec))

build_drivers() wraps embedding drivers in CachedEmbeddingDriver, so identical
texts only hit the backend once. Raise EmbeddingError when unconfigured — the
factory then skips the spec instead of failing the whole build.

See docs/drivers.md for the full driver contract.
"""

from __future__ import annotations

from typing import Any

from agentix.drivers.base import DriverDescriptor
from agentix.drivers.embedding import EmbeddingResult


class {class_name}:
    """Embedding driver for {name} — satisfies `agentix.drivers.embedding.EmbeddingDriver`."""

    name = "{key}"

    def __init__(self, *, spec: Any = None, api_key: str | None = None) -> None:
        self._spec = spec
        self._api_key = api_key
        self.model = getattr(spec, "model", None) or "CHANGEME"

    @property
    def descriptor(self) -> DriverDescriptor:
        return DriverDescriptor(
            name=self.name,
            type="model",
            modality="embedding",
            source="api",
            default_model=self.model,
        )

    async def embed(self, texts: list[str]) -> list[EmbeddingResult]:
        """Embed a batch of texts, one EmbeddingResult per input, in order.

        Vector length must be stable across calls of the same instance —
        the cosine index in agentix.storage.vector_index depends on it.
        """
        raise NotImplementedError("{class_name}.embed() not implemented")

    async def aclose(self) -> None:
        """Release underlying resources (HTTP clients, connections)."""
        return None


__all__ = ["{class_name}"]
'''

_STT_STUB = '''\
"""
{name} — speech-to-text driver stub generated by `agentix scaffold driver {name}`.

Implement `transcribe()`, then register (seam #13):

    from agentix.drivers.factory import register_driver_factory
    from {module_name} import {class_name}

    register_driver_factory("{key}", lambda spec, cfg: {class_name}(spec=spec))

See docs/drivers.md for the full driver contract.
"""

from __future__ import annotations

from typing import Any

from agentix.drivers.base import DriverDescriptor
from agentix.drivers.speech import AudioSource, Transcript


class {class_name}:
    """STT driver for {name} — satisfies `agentix.drivers.speech.SttDriver`."""

    name = "{key}"
    default_model = "CHANGEME"

    def __init__(self, *, spec: Any = None, api_key: str | None = None) -> None:
        self._spec = spec
        self._api_key = api_key
        if spec is not None and getattr(spec, "model", None):
            self.default_model = spec.model

    @property
    def descriptor(self) -> DriverDescriptor:
        return DriverDescriptor(
            name=self.name,
            type="model",
            modality="stt",
            source="api",
            default_model=self.default_model,
        )

    async def transcribe(self, source: AudioSource) -> Transcript:
        """Transcribe one audio source.

        `source.data` is raw bytes with `source.mime_type`; honour
        `source.model` as a per-call override of `default_model`, and
        `source.language` as a hint when the backend accepts one.
        """
        raise NotImplementedError("{class_name}.transcribe() not implemented")

    async def aclose(self) -> None:
        """Release underlying resources (HTTP clients, connections)."""
        return None


__all__ = ["{class_name}"]
'''

_STUBS: dict[str, str] = {
    "chat": _CHAT_STUB,
    "embedding": _EMBEDDING_STUB,
    "stt": _STT_STUB,
}


def _to_class_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_")) + "Driver"


def _to_key(name: str) -> str:
    return name.lower().replace("_", "-")


def _to_module(name: str) -> str:
    return name.lower().replace("-", "_")


def render_driver(name: str, modality: str) -> tuple[str, str]:
    """Return (filename, content) for a driver stub."""
    if modality not in _STUBS:
        raise ValueError(f"unknown modality {modality!r}; choose from: {list(_STUBS)}")
    template = _STUBS[modality]
    class_name = _to_class_name(name)
    key = _to_key(name)
    module_name = _to_module(name)
    content = template.format(name=name, class_name=class_name, key=key, module_name=module_name)
    filename = f"{module_name}.py"
    return filename, content
